import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.tsx'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	jsx: 'automatic',
	loader: {
		'.tsx': 'tsx',
		'.ts': 'ts',
		'.jsx': 'jsx',
		'.js': 'js',
		'.woff': 'file',
		'.woff2': 'file',
		'.ttf': 'file',
		'.otf': 'file'
	},
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		// Define globals that Chakra UI might need
		'global': 'globalThis',
	},
	alias: {
		'@': './src'
	},
	// Add banner to handle React JSX runtime for Chakra UI
	inject: ['./react-shim.js'],
	// Additional options for Chakra UI compatibility
	platform: 'browser',
	conditions: ['import', 'module', 'browser', 'default'],
	mainFields: ['browser', 'module', 'main'],
	resolveExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
	// Optimize bundle size for Chakra UI
	plugins: [
		{
			name: 'chakra-ui-optimizer',
			setup(build) {
				// Tree-shake unused Chakra UI components
				build.onResolve({ filter: /@chakra-ui/ }, (args) => {
					// Allow tree-shaking by preserving the original import
					return null;
				});
			}
		}
	]
});

// Create a react-shim.js file for JSX runtime if it doesn't exist
import { writeFileSync, existsSync } from 'fs';

if (!existsSync('./react-shim.js')) {
	writeFileSync('./react-shim.js', `
// React JSX runtime shim for esbuild
import React from 'react';
globalThis.React = React;
`);
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}